//! Bit-exact pins for geo.rs + polar.rs against the REAL lib/router.js,
//! generated by `node scripts/gen-geo-pins.mjs` (values are f64 bit
//! patterns straight from V8 running the actual engine source).

use meridian_sidecar::route::geo::{self, LL};
use meridian_sidecar::route::polar::{Polar, VesselPolar};

const NEWPORT: LL = LL { lat: 41.4945, lon: -71.3173 };
const STGEORGE: LL = LL { lat: 32.3833, lon: -64.675 };

fn assert_bits(actual: f64, expected_bits: u64, what: &str) {
    assert_eq!(
        actual.to_bits(),
        expected_bits,
        "{what}: got {actual:?} ({:#x}), JS pinned {:#x}",
        actual.to_bits(),
        expected_bits
    );
}

/// The J/120 default polar from lib/vessel.js (DEFAULT).
fn j120() -> VesselPolar {
    VesselPolar {
        twa: vec![28., 35., 45., 60., 75., 90., 110., 130., 150., 165., 180.],
        tws: vec![4., 6., 8., 10., 12., 14., 16., 20., 25.],
        bsp: vec![
            vec![3.0, 4.0, 4.5, 4.8, 5.0, 5.1, 5.2, 5.3, 5.2],
            vec![3.6, 4.7, 5.5, 5.9, 6.2, 6.3, 6.4, 6.5, 6.4],
            vec![4.2, 5.5, 6.3, 6.7, 6.9, 7.1, 7.2, 7.3, 7.2],
            vec![4.5, 6.0, 6.9, 7.4, 7.6, 7.8, 7.9, 8.0, 8.0],
            vec![4.6, 6.2, 7.2, 7.8, 8.0, 8.2, 8.3, 8.4, 8.4],
            vec![4.6, 6.2, 7.3, 8.0, 8.2, 8.4, 8.5, 8.6, 8.6],
            vec![4.3, 6.0, 7.2, 8.0, 8.4, 8.6, 8.7, 8.9, 8.9],
            vec![3.8, 5.6, 6.9, 7.8, 8.3, 8.6, 8.8, 9.0, 9.0],
            vec![3.1, 4.7, 6.0, 6.9, 7.5, 7.9, 8.2, 8.5, 8.5],
            vec![2.8, 4.2, 5.4, 6.3, 6.9, 7.3, 7.6, 8.0, 8.0],
            vec![2.6, 4.0, 5.0, 5.9, 6.5, 7.0, 7.4, 7.8, 7.8],
        ],
    }
}

#[test]
fn geo_pins() {
    assert_bits(geo::gc_distance(NEWPORT, STGEORGE), 0x4083c529c80703f9, "gcDistance");
    assert_bits(geo::bearing(NEWPORT, STGEORGE), 0x406276d152d95db4, "bearing");
    let w = geo::sphere_walk(NEWPORT, 123.45, 15.7);
    assert_bits(w.lat, 0x4044acccbaf1d247, "sphereWalk.lat");
    assert_bits(w.lon, 0xc051c1b4d0accb52, "sphereWalk.lon");
    assert_bits(geo::circ_diff(350.0, 10.0), 0x4034000000000000, "circDiff(350,10)");
    assert_bits(geo::circ_diff(10.0, 350.0), 0x4034000000000000, "circDiff(10,350)");
}

#[test]
fn polar_pins() {
    let p = Polar::new(&j120());
    assert_bits(p.bsp(47.3, 11.2), 0x401bb596de8ca11c, "polar close reach");
    assert_bits(p.bsp(200.0, 5.0), 0x400d111111111111, "polar fold >180");
    assert_bits(p.bsp(20.0, 8.0), 0x0000000000000000, "polar no-go cone");
    assert_bits(p.bsp(185.0, 30.0), 0x401f777777777777, "polar clamp high");
    assert_bits(p.bsp(-64.2, 17.9), 0x40201e76c8b43958, "polar negative twa");
}
